baseURL = "https://yanling-zhao.github.io/"
languageCode = 'en-us'
title = 'Yanling Zhao'
theme = 'notrack'
newContentEditor = "nvim"
# disqusShortname = "example"
paginate = 4


[params]
  siteHeading = "Yanling Zhao" # defaults to author
  favicon = "yz.png" # Adds a small icon next to the page title in a tab
  footer = "Copyright Â© Yanling Zhao 2022-2023. All Rights Reserved."
  [params.social]
    github = "Yanling-Zhao"
    linkedin = "yanling-zhao/"
    email = "lingzhao@bu.edu"
    twitter = "YanlingZhao_"
    googlescholar = "https://scholar.google.com/citations?hl=en&user=2O3hkjQAAAAJ"



[menu]
  [[menu.main]]
    identifier = "Projects"
     name = "Projects"
      weight = 200
       url = "#"
  
  
  [[menu.main]]
    identifier = "CV"
     name = "CV"
      weight = 400
       url = "https://acrobat.adobe.com/link/track?uri=urn:aaid:scds:US:5b61ef1f-2aa5-4a2e-87b5-c6b71e9a95ab"
       
  
